// @ts-check
// Fully autogenerated sidebar. This matters for the docs agent: it only ever writes
// Markdown files into ./docs (with frontmatter for title/position). It never has to edit
// this file, so a new doc appears in the sidebar automatically and there is no shared
// file for two proposals to conflict on.
//
// Ordering within a category is controlled per-doc via `sidebar_position` frontmatter,
// and per-folder via an optional `_category_.json`.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
